version: '3.7'
services:
  app:
    build:
      context: .
      args:
        spigot_version: 1.15.1
    command: ./start.sh
    environment:
      EULA: "false"
    ports:
      - "25565:25565"
    tty: true
    stdin_open: true

